var NameFactory = function() {
	var names = [
		'Ader Titsoff ',
		'Adolf Oliver Nipple',
		'Albee Fuctifino ',
		'Alotta Bush',
		'Alotta Fagina',
		'Alota Vagina ',
		'Amanda Bangor',
		'Amanda D. P. Throat',
		'Amanda Doomy',
		'Amanda Faulk',
		'Amanda Huginkiss',
		'Amanda Hump',
		'Amanda Lay',
		'Amanda Lick',
		'Amanda Mount',
		'Amanda Poker',
		'Ana Linjector',
		'Andy Felterbush ',
		'Andy Fetersnatch ',
		'Andy lickther ',
		'Andy Phuckterpuss ',
		'Andy Phucter',
		'Anita Bangor',
		'Anita B. Jaynow',
		'Anita B. Lojob',
		'Anita Bath',
		'Anita Blackman',
		'Anita Bohn',
		'Anita Bona ',
		'Anita Dick',
		'Anita Dickinme',
		'Anita Dump',
		'Anita Fuch',
		'Anna Gaspuwer ',
		'Anita Gofradump',
		'Anita Hanjaab',
		'Anita Hardcock',
		'Anita Head',
		'Anita Hoare',
		'Anita Hummer ',
		'Anita Jackoff',
		'Anita Lay',
		'Anita Little ',
		'Anita Longerman',
		'Anita Manda Ball ',
		'Anita Mandelay ',
		'Anita Masingil',
		'Anita Naylor',
		'Anita P. Ness',
		'Anita Pussy',
		'Anita Semen',
		'Anita Wackoff',
		'Anita Woodcock ',
		'Anita Woody',
		'Anita Wyderbox',
		'Anna Bortion',
		'Annie Position',
		'Annie Rection',
		'Anya Neeze',
		'Barry McCociner',
		'Barry McDikkin',
		'Barry Mapole ',
		'Bea Chermeat',
		'Ben Derhover',
		'Ben Dover',
		'Ben Gurgen Hoffe',
		'Ben Jackinoff',
		'Ben N. Syder',
		'Ben O. Verbich',
		'Ben R. Over',
		'Ben TimOver',
		'Andy Cornholder ',
		'Ben Wabawls',
		'Berry McCaulkiner',
		'Betty Bangzer',
		'Betty Drilzzer',
		'Betty Humpter',
		'Betty Phuckzer',
		'Betty Phucter ',
		'Betty Yeragoodlay ',
		'Bill Lowbiter',
		'Bo N. Herr',
		'Bo Nerr',
		'Brooke N. Rubbers',
		'Bruce D. Cocque',
		'Buck Nekkid',
		'Buster Cherry',
		'Buster Hymen',
		'C. Mike Rack',
		'Cantsia Weiner',
		'Chastity Belt',
		'Chris P. Nutts',
		'Claude Balls',
		'Clee Torres',
		'Clint Toris',
		'Cole Ostamie',
		'Colin Forsecs',
		'Connie Lingus',
		'Cox Ucker',
		'Craven Moorehead',
		'Curley Pubes',
		'Daisy May Blow',
		'Dang Lin-Wang',
		'Daryl B. Payne',
		'Dave Head ',
		'Dean Gil Barry',
		'Dee Flower',
		'Dia Rhea ',
		'Dick Aiken',
		'Dick Alred',
		'Dick Army ',
		'Dick Assman',
		'Dick Beiter ',
		'Dick Bender',
		'Dick Beninya',
		'Dick Brain',
		'Dick Burns',
		'Dick Bush',
		'Dick Butkus ',
		'Dick Cheese',
		'Dick C. Normus ',
		'Dick Cranium',
		'Dick Cumming',
		'Dick Cumoff',
		'Dick Daily',
		'Dick Eder',
		'Dick Encider ',
		'Dick Face',
		'Dick Finder',
		'Dick Fitzintite',
		'Dick Fitzinwell',
		'Dick Gozinya',
		'Dick Handler',
		'Dick Head',
		'Dick Hertz',
		'Dick Holder ',
		'Dick Hungwell',
		'Dick Hunter',
		'Dick Johnson',
		'Dick Kisser',
		'Dick Less',
		'Dick Lipps',
		'Dick Little',
		'Dick Long',
		'Dick Myaz',
		'Dick N. Butts',
		'Dick N. Cider',
		'Dick N. Snatch',
		'Dick Nose',
		'Dick Payne',
		'Dick Pole',
		'Dick Pound',
		'Dick Raasch',
		'Dick Ramdass',
		'Dick Rasch',
		'Dick Schwab',
		'Dick Scott Wood ',
		'Dick Seaman',
		'Dick Slocumb',
		'Dick Smack',
		'Dick Stick',
		'Dick Struck ',
		'Dick Sucker',
		'Dick Swett',
		'Dick Swollan',
		'Dick Tater',
		'Dick Trickle',
		'Dick Wacker',
		'Dick Wad',
		'Dick Weed',
		'Dick Zucker',
		'Dickie Chew ',
		'Dill Doe',
		'Dirk E. Sanchez ',
		'Dixie Normous',
		'Dixie Rect',
		'Dixon B. Tweenerlegs',
		'Dixon Butts',
		'Dixon Cox',
		'Dixon Hand',
		'Dixon Kuntz',
		'Don Keedix',
		'Doug McCockin',
		'Dougie Style',
		'Drew Peacock',
		'E. Jack Ulayte',
		'E. Norma Scock',
		'E. Norma Stits',
		'E. Normous Peter',
		'E. Rex Sean',
		'Eaton Beaver',
		'Edith D. Pussy',
		'Edith McCrotch',
		'Edith Mydick',
		'Eileen Ulick',
		'Elaine R. Over',
		'Emmerson Bigguns ',
		'Emmerson Littleuns ',
		'Emmerson Niceuns ',
		'Enorma Skank',
		'Eric Chin',
		'Eric Shun',
		'Eric Ted Long',
		'Eric Tyldisfunction',
		'Erin Gobraless',
		'Farr King',
		'Fawn Dell Maibalz',
		'Fawn Dillmiballs',
		'Fonda Cox',
		'Fonda Dix',
		'Fonda Peters',
		'Frank Lee Gay ',
		'Freida Brest',
		'Frida N. E. Wan ',
		'Fudd G. Packer',
		'Gay Barr',
		'Gerald Fitzpatrick',
		'Giv M. Head',
		'Gall E. McOxbig ',
		'Hans Omaicok',
		'Hans Updeskirt',
		'Harry A. Ness',
		'Harry Asscrack',
		'Harry Azcrac',
		'Harry Azzol',
		'Harry Balls',
		'Harry Ballsack',
		'Harry Ballsonya',
		'Harry Balzac',
		'Harry Balzitch',
		'Harry Beaver',
		'Harry Cox',
		'Harry Dick Hunter',
		'Harry Dix',
		'Harry Dong',
		'Harry Johnson',
		'Harry Kuntz',
		'Harry Nutt',
		'Harry P. Ness',
		'Harry Paratesties',
		'Harry Peters ',
		'Harry Reams',
		'Harry S. Balsak',
		'Harry S. Houle',
		'Harry Sach',
		'Harry Sax',
		'Harry Scrote',
		'Harry Setatesties',
		'Harry Weiner',
		'Harry Undersack ',
		'Haywood Jablomi',
		'Heywood Jagoblowhim ',
		'Heywood Japhucker ',
		'Heywood Japhuckhim ',
		'Heywood Jiblomy ',
		'Heidi Salami',
		'Helda Coccen-Mihan',
		'Helda Dick',
		'Helen Back',
		'Helen Bed',
		'Herb Eaverstinks',
		'Herb Utsmells',
		'Herbie Versmels',
		'Holden A. Pare',
		'Holden Dix and his wife Sharon Dix ',
		'Holden Hiscock',
		'Holden McGroin',
		'HO LEE FUK',
		'Honor Knees',
		'Houg Gebreasts',
		'Howie Feltersnatch',
		'Howie Phuckterpuss',
		'Howie Phucter ',
		'Hugh Beeotch',
		'Hugh G. Buttnoogie',
		'Hugh G. Dildeaux',
		'Hugh G. Rection',
		'Hugh Gass',
		'Hugh Gass Kisser',
		'Hugh Gebrests',
		'Hugh Gorgy',
		'Hugh Janus',
		'Hugh Jardon',
		'Hugh Jewnitt',
		'Hugh Jorgin',
		'Hugh Junit',
		'Hugh Fatasso ',
		'Hugh jass ',
		'Hugh Jorgan ',
		'Hugh Jorgasm ',
		'Hugh Jundys ',
		'Humphrey Lee',
		'Humphrey Willy',
		'Hyman Berston',
		'Homer Sexual',
		'I. Sal Balls',
		'I. Yankit',
		'I.C Yadick',
		'I. Fartatu ',
		'I. M. Hung ',
		'Iama Hore',
		'Ida Fucder',
		'Ilene Dover',
		'Ileen Forward ',
		'Ilova Gudfach',
		'Ima Buttmunch',
		'Ima Frute',
		'Ima Goodlay',
		'Ima Hoare',
		'Ima Homeau',
		'Ima Homo',
		'Ima Hooker',
		'Ima Horndawg',
		'Ima Horndog',
		'Ima P. Ness',
		'Ima Rapist',
		'Ima Reilly Cumming',
		'Iona Dick',
		'Iona Glasscock',
		'Iona P. Hole',
		'Issac Cox',
		'Issac Dick',
		'Iva Biggin',
		'Ivan Itchinanus',
		'Ivan Kutchakokov',
		'Ivan Yerkinov',
		'Ivana Cumalot',
		'Ivana Fucku',
		'Ivana Phuckalot ',
		'Ivanna Gitof ',
		'Ivana Gifa Laccio',
		'Ivana Hafsechs',
		'Ivana Havesex',
		'Ivana Hump',
		'Ivana Humpalot',
		'Ivana Shroomslap',
		'Ivanna B. Spanked',
		'Ivanna Humpalot',
		'Ivanna Jerkitov',
		'Ivanna Semour Butts',
		'Ivanna Threesum',
		'Ivanna Tinkle',
		'Ivona Screw',
		'Iwonna Ryder',
		'John Arhea',
		'Jack Goff',
		'Jack Hoffer',
		'Jack Inoff',
		'Jack Knauf',
		'Jack Mehoff',
		'Jack Ma Wang ',
		'Jack Mahogoff ',
		'Jack Schitt',
		'Jack SlapperAskie ',
		'Jack Soffalot',
		'Jacques Off',
		'Jacques Sheet ',
		'Jason Pussy',
		'Jawanna Blowme ',
		'Jen Etzel',
		'Jen Italworts',
		'Jenny Taylia',
		'Jenny Tull Warts',
		'Jenny Tulworts',
		'Jew C. Tuatt',
		'Jocelyn Cocque',
		'Joe Blosus',
		'John Outhouse ',
		'Joy Ryde-Myaz',
		'Justin DeFront',
		'Justin Heranus',
		'Justin Herass',
		'Justin Hermouth',
		'Justin Yermouth',
		' Kenya Swallow',
		'Kareem M. Pants',
		'Kari Mysac',
		'Kimmy Hed',
		'Lar G. Rection',
		'Layla Konswallow',
		'Les Bea Anne Lovers',
		'Lisa Swallow ',
		'Liz Bien',
		'Long Medick ',
		'Lotta Cox ',
		'Lotta Hore ',
		'Lou C. Twatt',
		'Lou Sanus',
		'Lou Sass',
		'Lou Skunt',
		'Lou Stools',
		'Lou Spussy ',
		'Lou Swimmin',
		'Lube McCock',
		'Lucy Bowels',
		'Minnie Pad',
		'Madam Dick Burns',
		'Madam Dick Itches',
		'Madame Cocburns',
		'Madame Crotch',
		'Madame Dick Burns',
		'Manley Balls ',
		'Manaj A. Twaa',
		'Manny Kanblo',
		'Martha Fokker',
		'Master Bates',
		'Mat Sterbator',
		'Matt Sterbate',
		'Maud R. Fokker',
		'Major, Dick Holder ',
		'Max E. Pad',
		'May I. Tutchem',
		'Maya Achinballs',
		'Mel Ester',
		'Mia Buttreeks',
		'Michael Toris',
		'Mike Hawk ',
		'Mike Hockertz',
		'Mike Hunt',
		'Mike Littisore',
		'Mike Litoris ',
		'Mike Ockinyu ',
		'Mike Oxawopper',
		'Mike Oxhard',
		'Mike Oxlittle',
		'Mike Oxlong',
		'Mike Oxsbig',
		'Mike Oxtinx',
		'Mike Rotch',
		'Mike Rotchburns',
		'Miles Long',
		'Mister Hyman',
		'Mister Period',
		'Moe Lester',
		'Mona Little',
		'Mona Lott',
		'Monica Blewbillski',
		'M.T. Sack ',
		'Mr. Bation',
		'Mr. Completely',
		'Mrs. Hiscock',
		'Mya Blousfalopan ',
		'Mysha Long',
		'N. Joey Magoo ',
		'Neil Anblomee',
		'Neil Anblomi',
		'Neil Down',
		'Neil Enbob',
		'Neil Enlick',
		'Neil Ensuck',
		'Neil Gaiman',
		'Neil Inlick',
		'Neil Zineatser',
		'Nick Eyres ',
		'Nida Pee',
		'Norma Snockers',
		'Norma Stits',
		'Niel Anblowme',
		'Noe Schitt-Sherlock',
		'O. Howie Dickter',
		'Oliver Bush ',
		'Oliver Closeoff',
		'Oliver Clozov',
		'Onostatio Beaverhousen ',
		'Ophelia Nutz',
		'Ophelia Balls',
		'Ophelia Cox',
		'Ophelia Cuming',
		'Ophelia Rass',
		'Ophillia Balls',
		'Otto B. Astripper',
		'P Hole',
		'P. Enis Meany',
		'P. Ness',
		'P. Nisevny',
		'Pat Herboub',
		'Pat Hiscock',
		'Pat Maweini',
		'Pat McCock ',
		'Pat McGroin',
		'Pat McHunt ',
		'Pat York Hunt ',
		'Pat McRotch',
		'Pat Myaz',
		'Patrick Fitzgerald',
		'Penny Tration',
		'Pete O\'File',
		'Peter Beter',
		'Peter Breath ',
		'Peter Dragon ',
		'Peter Fitzinwell',
		'Peter Gosinya ',
		'Peter Insidya',
		'Peter Johnson',
		'Peter Usedenuf',
		'Phil A. Show',
		'Phil Accio',
		'Phil Atio',
		'Phil C. Rottencrotch',
		'Phil McAvity',
		'Phil McCrackin',
		'Phil McCreviss',
		'Phil McCrotch',
		'Phil Mianus',
		'Phil Mycaulk',
		'Philis Ardon',
		'Phillip A. Butt',
		'Phillip Herpanties ',
		'Phill Herbutt ',
		'Phillip McCrack',
		'Phill McHunt',
		'Philip Herass ',
		'Phillip Mipanties',
		'Phillip Oliver Holz',
		'Phillip Oliver Krevises',
		'Phillip Purass',
		'Phuc N. Stupid',
		'Poppa Woody',
		'Pussy Galore',
		'Rosie O\' Kunt',
		'Richard Cranium',
		'Ram Dass',
		'Ran Sidass',
		'Randy Peter',
		'Ray Pugh',
		'Robert Ennema ',
		'Rob McLitoris ',
		'Rhoda Duck',
		'Rhoda Hotte',
		'Ricardo Cabeza',
		'Rhoda Hardcock ',
		'Rocco Z. Caulk',
		'Roch Myaz',
		'Rod Gozinya',
		'Rod Stiffington ',
		'Roland D\'Hay',
		'Rolen Thehay',
		'Rolinda Bitches ',
		'Rolinda Joint ',
		'Ron Chee',
		'Rosie Palm',
		'Ross Crodum',
		'Ruben Mycock',
		'Rueben G. Spaut',
		'Rueben Z. Clitz',
		'Rusty Kuntz',
		'Sal T. Rection',
		'Sarah Tonin',
		'Sawyer Crack',
		'Sawyer Snatch',
		'Scott Hiscock',
		'Seaman Sample',
		'Seaman Staines ',
		'Seymore Butts ',
		'Semour Asscrack',
		'Seymour Snatch',
		'Seymour Weiner ',
		'Shara Dick',
		'Sharon Cox',
		'Sharon Head',
		'Sharon Peters',
		'Shea Verpussi',
		'Sophanda Peters',
		'Stacy Rect',
		'Stella Virgin',
		'Stikit Inya',
		'Stu Pidass',
		'Stu Pidassoe',
		'Sylfilthia Rottencrotch',
		'Sylvia Dooble-Fitz',
		'Tara Nupsumass',
		'Tal E. Whacker',
		'Tara Dickoff',
		'Tara Himen',
		'Tara Holenme',
		'Tara McClosoff',
		'Tara Scrodum',
		'Tess Eckel',
		'Tess Tickles',
		'Todd Lerfondler ',
		'Toss Misalad',
		'Tony Handcock ',
		'U. R. Stuck',
		'Vye Agra',
		'Vye Brator',
		'Wang Phat',
		'Wan Ta Rim ',
		'Wanda Rimmer',
		'Watson Herbusch',
		'Wayne Kerr',
		'Will Liciipanti',
		'Willie B. Hardigan',
		'Willie Dicker',
		'Willie Eatmeout',
		'Willie Fisterbottom',
		'Willie Focker',
		'Willie Layer',
		'Wilma Dickfit',
		'Wilma Fingerdoo',
		'Wilma Handue',
		'Will U. Suckminuts ',
		'Woody Viagra',
		'Zig Steenine',
		'Yandeeda Horgasm',
		'York Hunt'
	];
	
	this.generate = function() {
		return names[Math.floor(Math.random() * names.length)];
	}
}

module.exports = NameFactory;